sudo: required
language: ruby
cache:
  bundler: true
# addons:
#   postgresql: "10.8"
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
script:
- bundle install
- yarn install
- RAILS_ENV=test bundle exec rake db:create db:migrate
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t simplecov --id $CC_TEST_REPORTER_ID"
